"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from typing import TypedDict
from wayfaster.types import BaseModel


class CreateSessionsResponseTypedDict(TypedDict):
    id: str


class CreateSessionsResponse(BaseModel):
    id: str
