"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from typing import TypedDict
from typing_extensions import Annotated
from wayfaster.types import BaseModel
from wayfaster.utils import FieldMetadata, PathParamMetadata


class ReadInterviewConfigInterviewConfigsIDGetRequestTypedDict(TypedDict):
    id: str


class ReadInterviewConfigInterviewConfigsIDGetRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
