"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from typing import Optional, TypedDict
from typing_extensions import Annotated, NotRequired
from wayfaster.types import BaseModel
from wayfaster.utils import FieldMetadata, SecurityMetadata


class SecurityTypedDict(TypedDict):
    username: NotRequired[str]
    password: NotRequired[str]


class Security(BaseModel):
    username: Annotated[
        Optional[str],
        FieldMetadata(
            security=SecurityMetadata(
                scheme=True, scheme_type="http", sub_type="basic", field_name="username"
            )
        ),
    ] = None

    password: Annotated[
        Optional[str],
        FieldMetadata(
            security=SecurityMetadata(
                scheme=True, scheme_type="http", sub_type="basic", field_name="password"
            )
        ),
    ] = None
