openapi: 3.1.0
info:
  title: FastAPI
  version: 0.1.0
servers:
  - url: https://api.techinterviewer.ai
    description: The production API
paths:
  /interview-configs:
    get:
      summary: Read Interview Configs
      operationId: read_interview_configs_interview_configs_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
      security:
        - HTTPBasic: []
      x-speakeasy-group: interviewConfigs
      x-speakeasy-name-override: list
  /interview-configs/{id}:
    get:
      summary: Read Interview Config
      operationId: read_interview_config_interview_configs__id__get
      security:
        - HTTPBasic: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            title: Id
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      x-speakeasy-group: interviewConfigs
      x-speakeasy-name-override: get
  /create_session:
    post:
      summary: Create Session
      operationId: create_session_create_session_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateSessionsRequestBody'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      security:
        - HTTPBasic: []
      x-speakeasy-group: sessions
      x-speakeasy-name-override: createSession
  /sessions:
    post:
      summary: Read Sessions
      operationId: read_sessions_sessions_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReadSessionsRequestBody'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      security:
        - HTTPBasic: []
      x-speakeasy-group: sessions
      x-speakeasy-name-override: create
  /sessions/{id}:
    get:
      summary: Read Session
      operationId: read_session_sessions__id__get
      security:
        - HTTPBasic: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            title: Id
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      x-speakeasy-group: sessions
      x-speakeasy-name-override: get
components:
  schemas:
    CreateSessionsRequestBody:
      properties:
        interview_config_id:
          type: string
          title: Interview Config Id
      type: object
      required:
        - interview_config_id
      title: CreateSessionsRequestBody
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    ReadSessionsRequestBody:
      properties:
        interview_config_id:
          type: string
          title: Interview Config Id
      type: object
      required:
        - interview_config_id
      title: ReadSessionsRequestBody
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
              - type: string
              - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
        - loc
        - msg
        - type
      title: ValidationError
  securitySchemes:
    HTTPBasic:
      type: http
      scheme: basic
